// TriviaQuestions.swift — Static question bank for Trivia game
// TriviaCategory and TriviaDifficulty are defined in Engine/TriviaGame.swift

enum TriviaQuestionBank {
    static var all: [TriviaQ] { science + history + geography + sports + movies + music + literature + technology + food + art }

    static func byID(_ id: Int) -> TriviaQ? { all.first { $0.id == id } }

    // MARK: — Science (1000–1099)
    private static var science: [TriviaQ] {[
        TriviaQ(id: 1001, cat: .science, diff: .easy, q: "What is the chemical symbol for gold?", a: ["Au","Ag","Fe","Cu"], c: 0),
        TriviaQ(id: 1002, cat: .science, diff: .easy, q: "How many bones are in the adult human body?", a: ["196","206","216","226"], c: 1),
        TriviaQ(id: 1003, cat: .science, diff: .easy, q: "What planet is known as the Red Planet?", a: ["Venus","Jupiter","Mars","Saturn"], c: 2),
        TriviaQ(id: 1004, cat: .science, diff: .easy, q: "What gas do plants absorb from the atmosphere during photosynthesis?", a: ["Oxygen","Nitrogen","Carbon dioxide","Hydrogen"], c: 2),
        TriviaQ(id: 1005, cat: .science, diff: .easy, q: "What is the center of an atom called?", a: ["Electron","Neutron","Proton","Nucleus"], c: 3),
        TriviaQ(id: 1006, cat: .science, diff: .easy, q: "What is the boiling point of water at sea level in Celsius?", a: ["90°C","95°C","100°C","105°C"], c: 2),
        TriviaQ(id: 1007, cat: .science, diff: .easy, q: "What organ pumps blood through the human body?", a: ["Liver","Lungs","Kidney","Heart"], c: 3),
        TriviaQ(id: 1008, cat: .science, diff: .easy, q: "What is the chemical formula for water?", a: ["HO","H2O","H3O","H2O2"], c: 1),
        TriviaQ(id: 1009, cat: .science, diff: .easy, q: "How many planets are in our solar system?", a: ["7","8","9","10"], c: 1),
        TriviaQ(id: 1010, cat: .science, diff: .easy, q: "What is the largest organ in the human body?", a: ["Liver","Brain","Intestine","Skin"], c: 3),
        TriviaQ(id: 1011, cat: .science, diff: .easy, q: "What force keeps planets in orbit around the sun?", a: ["Magnetism","Friction","Gravity","Electrostatics"], c: 2),
        TriviaQ(id: 1012, cat: .science, diff: .easy, q: "What type of blood cells carry oxygen?", a: ["White blood cells","Platelets","Red blood cells","Plasma cells"], c: 2),
        TriviaQ(id: 1013, cat: .science, diff: .easy, q: "What is the nearest star to Earth?", a: ["Alpha Centauri","Sirius","Proxima Centauri","The Sun"], c: 3),
        TriviaQ(id: 1014, cat: .science, diff: .easy, q: "What is the chemical symbol for oxygen?", a: ["Ox","O","Om","Or"], c: 1),
        TriviaQ(id: 1015, cat: .science, diff: .easy, q: "What part of a plant conducts photosynthesis?", a: ["Root","Stem","Leaf","Flower"], c: 2),
        TriviaQ(id: 1016, cat: .science, diff: .medium, q: "What is the atomic number of carbon?", a: ["4","6","8","12"], c: 1),
        TriviaQ(id: 1017, cat: .science, diff: .medium, q: "What is the speed of light in a vacuum (approx.)?", a: ["200,000 km/s","299,792 km/s","310,000 km/s","350,000 km/s"], c: 1),
        TriviaQ(id: 1018, cat: .science, diff: .medium, q: "What scientist formulated the theory of general relativity?", a: ["Isaac Newton","Niels Bohr","Albert Einstein","Max Planck"], c: 2),
        TriviaQ(id: 1019, cat: .science, diff: .medium, q: "What is the powerhouse of the cell?", a: ["Ribosome","Nucleus","Mitochondria","Golgi apparatus"], c: 2),
        TriviaQ(id: 1020, cat: .science, diff: .medium, q: "Which element has the symbol 'Fe'?", a: ["Fluorine","Francium","Iron","Fermium"], c: 2),
        TriviaQ(id: 1021, cat: .science, diff: .medium, q: "What is the half-life of Carbon-14?", a: ["1,000 years","5,730 years","10,000 years","14,000 years"], c: 1),
        TriviaQ(id: 1022, cat: .science, diff: .medium, q: "What is the process by which liquids turn to gas?", a: ["Condensation","Sublimation","Evaporation","Precipitation"], c: 2),
        TriviaQ(id: 1023, cat: .science, diff: .medium, q: "How many chromosomes does a typical human cell have?", a: ["23","44","46","48"], c: 2),
        TriviaQ(id: 1024, cat: .science, diff: .medium, q: "What is Newton's Second Law of Motion?", a: ["For every action there is an equal and opposite reaction","An object in motion stays in motion","F = ma","Energy cannot be created or destroyed"], c: 2),
        TriviaQ(id: 1025, cat: .science, diff: .medium, q: "What is the most abundant element in Earth's crust?", a: ["Silicon","Iron","Aluminum","Oxygen"], c: 3),
        TriviaQ(id: 1026, cat: .science, diff: .medium, q: "What type of wave is sound?", a: ["Transverse","Longitudinal","Electromagnetic","Gravitational"], c: 1),
        TriviaQ(id: 1027, cat: .science, diff: .medium, q: "What is the pH of a neutral solution?", a: ["0","7","10","14"], c: 1),
        TriviaQ(id: 1028, cat: .science, diff: .medium, q: "What gas makes up about 78% of Earth's atmosphere?", a: ["Oxygen","Carbon dioxide","Argon","Nitrogen"], c: 3),
        TriviaQ(id: 1029, cat: .science, diff: .medium, q: "What organ produces insulin?", a: ["Liver","Kidneys","Pancreas","Spleen"], c: 2),
        TriviaQ(id: 1030, cat: .science, diff: .medium, q: "What is the process called when DNA copies itself?", a: ["Transcription","Translation","Replication","Mutation"], c: 2),
        TriviaQ(id: 1031, cat: .science, diff: .medium, q: "What is the unit of electrical resistance?", a: ["Volt","Ampere","Watt","Ohm"], c: 3),
        TriviaQ(id: 1032, cat: .science, diff: .medium, q: "What is the name of the boundary between Earth's core and mantle?", a: ["Moho discontinuity","Lehmann discontinuity","Gutenberg discontinuity","Conrad discontinuity"], c: 2),
        TriviaQ(id: 1033, cat: .science, diff: .hard, q: "What is the Chandrasekhar limit?", a: ["1.0 solar masses","1.4 solar masses","2.0 solar masses","3.0 solar masses"], c: 1),
        TriviaQ(id: 1034, cat: .science, diff: .hard, q: "What subatomic particle was discovered at CERN in 2012?", a: ["Z boson","W boson","Higgs boson","Top quark"], c: 2),
        TriviaQ(id: 1035, cat: .science, diff: .hard, q: "What is the Krebs cycle also known as?", a: ["Glycolysis cycle","Citric acid cycle","Calvin cycle","Urea cycle"], c: 1),
        TriviaQ(id: 1036, cat: .science, diff: .hard, q: "Which law states that the pressure of a gas is inversely proportional to its volume at constant temperature?", a: ["Charles's Law","Gay-Lussac's Law","Boyle's Law","Avogadro's Law"], c: 2),
        TriviaQ(id: 1037, cat: .science, diff: .hard, q: "What is the name of the process that converts nitrogen gas into ammonia?", a: ["Nitrification","Haber-Bosch process","Denitrification","Nitrogen fixation by rhizobia"], c: 1),
        TriviaQ(id: 1038, cat: .science, diff: .hard, q: "What is Avogadro's number?", a: ["6.022 × 10²²","6.022 × 10²³","6.022 × 10²⁴","3.011 × 10²³"], c: 1),
        TriviaQ(id: 1039, cat: .science, diff: .hard, q: "What phenomenon explains the bending of light around massive objects?", a: ["Refraction","Diffraction","Gravitational lensing","Chromatic aberration"], c: 2),
        TriviaQ(id: 1040, cat: .science, diff: .easy, q: "What is the closest planet to the Sun?", a: ["Venus","Mercury","Earth","Mars"], c: 1),
        TriviaQ(id: 1041, cat: .science, diff: .easy, q: "What is the most common blood type?", a: ["A+","B+","O+","AB+"], c: 2),
        TriviaQ(id: 1042, cat: .science, diff: .medium, q: "What is the name of the process by which rocks are broken down by weather?", a: ["Erosion","Deposition","Weathering","Sedimentation"], c: 2),
        TriviaQ(id: 1043, cat: .science, diff: .medium, q: "What element is a diamond made of?", a: ["Silicon","Carbon","Graphite","Quartz"], c: 1),
        TriviaQ(id: 1044, cat: .science, diff: .medium, q: "What is the name of the protein that carries oxygen in red blood cells?", a: ["Keratin","Myosin","Hemoglobin","Insulin"], c: 2),
        TriviaQ(id: 1045, cat: .science, diff: .hard, q: "What is the Schrödinger equation used to describe?", a: ["Quantum state of a physical system","Relativistic motion of particles","Thermodynamic entropy","Electromagnetic field propagation"], c: 0),
        TriviaQ(id: 1046, cat: .science, diff: .medium, q: "What layer of Earth's atmosphere does weather occur in?", a: ["Stratosphere","Mesosphere","Troposphere","Thermosphere"], c: 2),
        TriviaQ(id: 1047, cat: .science, diff: .easy, q: "What is the chemical symbol for sodium?", a: ["So","Na","Sd","Sm"], c: 1),
        TriviaQ(id: 1048, cat: .science, diff: .medium, q: "What is the study of fungi called?", a: ["Botany","Mycology","Phycology","Zoology"], c: 1),
        TriviaQ(id: 1049, cat: .science, diff: .hard, q: "What is the Pauli exclusion principle?", a: ["No two electrons can occupy the same quantum state simultaneously","Electrons orbit the nucleus in fixed paths","Energy is quantized in discrete packets","The uncertainty principle for particles"], c: 0),
        TriviaQ(id: 1050, cat: .science, diff: .medium, q: "What is the hottest planet in our solar system?", a: ["Mercury","Earth","Venus","Jupiter"], c: 2),
    ]}

    // MARK: — History (2000–2099)
    private static var history: [TriviaQ] {[
        TriviaQ(id: 2001, cat: .history, diff: .easy, q: "In what year did World War II end?", a: ["1943","1944","1945","1946"], c: 2),
        TriviaQ(id: 2002, cat: .history, diff: .easy, q: "Who was the first President of the United States?", a: ["John Adams","Thomas Jefferson","Benjamin Franklin","George Washington"], c: 3),
        TriviaQ(id: 2003, cat: .history, diff: .easy, q: "What ancient wonder was located in Alexandria, Egypt?", a: ["Hanging Gardens","Colossus of Rhodes","The Lighthouse","Temple of Artemis"], c: 2),
        TriviaQ(id: 2004, cat: .history, diff: .easy, q: "Who was the first man to walk on the moon?", a: ["Buzz Aldrin","Yuri Gagarin","Neil Armstrong","John Glenn"], c: 2),
        TriviaQ(id: 2005, cat: .history, diff: .easy, q: "In what year did the Berlin Wall fall?", a: ["1987","1988","1989","1991"], c: 2),
        TriviaQ(id: 2006, cat: .history, diff: .easy, q: "Which empire built the Colosseum in Rome?", a: ["Greek Empire","Ottoman Empire","Roman Empire","Byzantine Empire"], c: 2),
        TriviaQ(id: 2007, cat: .history, diff: .easy, q: "Who wrote the Declaration of Independence?", a: ["George Washington","Benjamin Franklin","Alexander Hamilton","Thomas Jefferson"], c: 3),
        TriviaQ(id: 2008, cat: .history, diff: .easy, q: "In what year did World War I begin?", a: ["1912","1913","1914","1916"], c: 2),
        TriviaQ(id: 2009, cat: .history, diff: .easy, q: "What ship sank in 1912 after hitting an iceberg?", a: ["Lusitania","Britannic","Olympic","Titanic"], c: 3),
        TriviaQ(id: 2010, cat: .history, diff: .easy, q: "Who was the Egyptian queen famous for her relationship with Julius Caesar and Mark Antony?", a: ["Nefertiti","Hatshepsut","Cleopatra","Isis"], c: 2),
        TriviaQ(id: 2011, cat: .history, diff: .medium, q: "What year did the American Civil War begin?", a: ["1859","1861","1863","1865"], c: 1),
        TriviaQ(id: 2012, cat: .history, diff: .medium, q: "Which country did Napoleon Bonaparte conquer in 1798 before being defeated at the Battle of the Nile?", a: ["Italy","Spain","Egypt","Prussia"], c: 2),
        TriviaQ(id: 2013, cat: .history, diff: .medium, q: "Who was the first woman to win a Nobel Prize?", a: ["Rosalind Franklin","Marie Curie","Florence Nightingale","Ada Lovelace"], c: 1),
        TriviaQ(id: 2014, cat: .history, diff: .medium, q: "What ancient civilization built Machu Picchu?", a: ["Aztec","Maya","Olmec","Inca"], c: 3),
        TriviaQ(id: 2015, cat: .history, diff: .medium, q: "In what year did the French Revolution begin?", a: ["1776","1785","1789","1793"], c: 2),
        TriviaQ(id: 2016, cat: .history, diff: .medium, q: "Who was the leader of the Soviet Union during World War II?", a: ["Lenin","Trotsky","Stalin","Khrushchev"], c: 2),
        TriviaQ(id: 2017, cat: .history, diff: .medium, q: "What document, signed in 1215, limited the power of the English king?", a: ["Bill of Rights","Magna Carta","Habeas Corpus Act","Petition of Right"], c: 1),
        TriviaQ(id: 2018, cat: .history, diff: .medium, q: "Which explorer was the first European to reach India by sea?", a: ["Christopher Columbus","Ferdinand Magellan","Vasco da Gama","Bartholomeu Dias"], c: 2),
        TriviaQ(id: 2019, cat: .history, diff: .medium, q: "What was the name of the first artificial satellite launched into space?", a: ["Explorer 1","Vostok","Sputnik 1","Luna 1"], c: 2),
        TriviaQ(id: 2020, cat: .history, diff: .medium, q: "In which city was the Archduke Franz Ferdinand assassinated in 1914?", a: ["Vienna","Prague","Budapest","Sarajevo"], c: 3),
        TriviaQ(id: 2021, cat: .history, diff: .hard, q: "What was the name of the conspiracy to assassinate Hitler in July 1944?", a: ["Operation Valkyrie","Operation Overlord","Operation Barbarossa","Operation Sea Lion"], c: 0),
        TriviaQ(id: 2022, cat: .history, diff: .hard, q: "Who was the Roman general who crossed the Rubicon in 49 BC?", a: ["Pompey","Marcus Crassus","Julius Caesar","Mark Antony"], c: 2),
        TriviaQ(id: 2023, cat: .history, diff: .hard, q: "What treaty ended the Thirty Years' War in 1648?", a: ["Treaty of Utrecht","Peace of Westphalia","Treaty of Versailles","Congress of Vienna"], c: 1),
        TriviaQ(id: 2024, cat: .history, diff: .medium, q: "Who was the first Emperor of China?", a: ["Wu Zetian","Liu Bang","Qin Shi Huang","Emperor Yao"], c: 2),
        TriviaQ(id: 2025, cat: .history, diff: .easy, q: "What famous wall was built to protect ancient China from northern invasions?", a: ["Hadrian's Wall","Great Wall of China","Wall of Babylon","Aurelian Wall"], c: 1),
        TriviaQ(id: 2026, cat: .history, diff: .medium, q: "Who delivered the 'I Have a Dream' speech in 1963?", a: ["Malcolm X","Medgar Evers","Thurgood Marshall","Martin Luther King Jr."], c: 3),
        TriviaQ(id: 2027, cat: .history, diff: .hard, q: "What battle in 1815 ended the Napoleonic Wars?", a: ["Battle of Leipzig","Battle of Austerlitz","Battle of Trafalgar","Battle of Waterloo"], c: 3),
        TriviaQ(id: 2028, cat: .history, diff: .medium, q: "What year was the United Nations founded?", a: ["1943","1944","1945","1948"], c: 2),
        TriviaQ(id: 2029, cat: .history, diff: .easy, q: "Who was the leader of Nazi Germany during World War II?", a: ["Heinrich Himmler","Hermann Göring","Joseph Goebbels","Adolf Hitler"], c: 3),
        TriviaQ(id: 2030, cat: .history, diff: .medium, q: "Which U.S. President signed the Emancipation Proclamation?", a: ["Ulysses S. Grant","Andrew Johnson","James Buchanan","Abraham Lincoln"], c: 3),
        TriviaQ(id: 2031, cat: .history, diff: .hard, q: "Who was the Byzantine Emperor when Constantinople fell in 1453?", a: ["Constantine XI","Justinian II","Basil II","John VIII"], c: 0),
        TriviaQ(id: 2032, cat: .history, diff: .medium, q: "What was the name of the first permanent English settlement in America?", a: ["Plymouth","Roanoke","Jamestown","Boston"], c: 2),
        TriviaQ(id: 2033, cat: .history, diff: .medium, q: "The Opium Wars in the 19th century were fought between China and which country?", a: ["France","United States","Britain","Portugal"], c: 2),
        TriviaQ(id: 2034, cat: .history, diff: .easy, q: "In what year did Christopher Columbus reach the Americas?", a: ["1488","1490","1492","1498"], c: 2),
        TriviaQ(id: 2035, cat: .history, diff: .hard, q: "What was the name of the ancient trade route connecting China to the Mediterranean?", a: ["Amber Road","Silk Road","Spice Route","Incense Trail"], c: 1),
        TriviaQ(id: 2036, cat: .history, diff: .medium, q: "Which empire was known as the 'Ottoman Empire'?", a: ["Persian Empire","Turkish Empire","Arabian Empire","Mughal Empire"], c: 1),
        TriviaQ(id: 2037, cat: .history, diff: .easy, q: "What was the name of the D-Day invasion in WWII?", a: ["Operation Barbarossa","Operation Market Garden","Operation Overlord","Operation Torch"], c: 2),
        TriviaQ(id: 2038, cat: .history, diff: .medium, q: "Who was the first woman to fly solo across the Atlantic Ocean?", a: ["Bessie Coleman","Jacqueline Cochran","Harriet Quimby","Amelia Earhart"], c: 3),
        TriviaQ(id: 2039, cat: .history, diff: .hard, q: "What civilization developed the first written law code, the Code of Ur-Nammu?", a: ["Babylonian","Sumerian","Egyptian","Akkadian"], c: 1),
        TriviaQ(id: 2040, cat: .history, diff: .medium, q: "During which decade did the Cold War end?", a: ["1970s","1980s","1990s","2000s"], c: 1),
        TriviaQ(id: 2041, cat: .history, diff: .easy, q: "What country dropped the atomic bombs on Japan in 1945?", a: ["Britain","Soviet Union","United States","France"], c: 2),
        TriviaQ(id: 2042, cat: .history, diff: .medium, q: "What was the first country to grant women the right to vote?", a: ["United States","Britain","Australia","New Zealand"], c: 3),
        TriviaQ(id: 2043, cat: .history, diff: .hard, q: "The Battle of Thermopylae in 480 BC was fought between Persia and which Greek city-state?", a: ["Athens","Corinth","Thebes","Sparta"], c: 3),
        TriviaQ(id: 2044, cat: .history, diff: .medium, q: "What was the name of the Soviet space mission that put the first human in space?", a: ["Soyuz 1","Vostok 1","Mercury 1","Cosmos 1"], c: 1),
        TriviaQ(id: 2045, cat: .history, diff: .hard, q: "Who was the Mongol ruler who founded the largest contiguous land empire in history?", a: ["Kublai Khan","Tamerlane","Attila the Hun","Genghis Khan"], c: 3),
        TriviaQ(id: 2046, cat: .history, diff: .medium, q: "What year was the Eiffel Tower completed?", a: ["1885","1887","1889","1893"], c: 2),
        TriviaQ(id: 2047, cat: .history, diff: .easy, q: "Which country was known as 'Persia' historically?", a: ["Iraq","Turkey","Iran","Afghanistan"], c: 2),
        TriviaQ(id: 2048, cat: .history, diff: .medium, q: "Who was the British Prime Minister during most of World War II?", a: ["Neville Chamberlain","Clement Attlee","Anthony Eden","Winston Churchill"], c: 3),
        TriviaQ(id: 2049, cat: .history, diff: .hard, q: "What was the name of the Roman gladiator who led a slave revolt in 73 BC?", a: ["Hannibal","Crixus","Spartacus","Vercingetorix"], c: 2),
        TriviaQ(id: 2050, cat: .history, diff: .medium, q: "What was the name of the plan that provided U.S. economic aid to Europe after WWII?", a: ["Truman Doctrine","Lend-Lease Act","Marshall Plan","Bretton Woods Agreement"], c: 2),
    ]}

    // MARK: — Geography (3000–3099)
    private static var geography: [TriviaQ] {[
        TriviaQ(id: 3001, cat: .geography, diff: .easy, q: "What is the capital of France?", a: ["Lyon","Marseille","Paris","Bordeaux"], c: 2),
        TriviaQ(id: 3002, cat: .geography, diff: .easy, q: "What is the largest country in the world by area?", a: ["Canada","China","United States","Russia"], c: 3),
        TriviaQ(id: 3003, cat: .geography, diff: .easy, q: "What is the longest river in the world?", a: ["Amazon","Congo","Mississippi","Nile"], c: 3),
        TriviaQ(id: 3004, cat: .geography, diff: .easy, q: "What is the highest mountain in the world?", a: ["K2","Kangchenjunga","Mount Everest","Lhotse"], c: 2),
        TriviaQ(id: 3005, cat: .geography, diff: .easy, q: "What is the capital of Japan?", a: ["Osaka","Kyoto","Hiroshima","Tokyo"], c: 3),
        TriviaQ(id: 3006, cat: .geography, diff: .easy, q: "What is the smallest country in the world?", a: ["Monaco","San Marino","Liechtenstein","Vatican City"], c: 3),
        TriviaQ(id: 3007, cat: .geography, diff: .easy, q: "On which continent is the Sahara Desert located?", a: ["Asia","South America","Australia","Africa"], c: 3),
        TriviaQ(id: 3008, cat: .geography, diff: .easy, q: "What ocean is the largest in the world?", a: ["Atlantic","Indian","Arctic","Pacific"], c: 3),
        TriviaQ(id: 3009, cat: .geography, diff: .easy, q: "What is the capital of Australia?", a: ["Sydney","Melbourne","Brisbane","Canberra"], c: 3),
        TriviaQ(id: 3010, cat: .geography, diff: .easy, q: "What river flows through Egypt?", a: ["Tigris","Euphrates","Niger","Nile"], c: 3),
        TriviaQ(id: 3011, cat: .geography, diff: .medium, q: "What is the capital of Canada?", a: ["Toronto","Vancouver","Montreal","Ottawa"], c: 3),
        TriviaQ(id: 3012, cat: .geography, diff: .medium, q: "What is the largest desert in the world?", a: ["Sahara","Gobi","Antarctic","Arabian"], c: 2),
        TriviaQ(id: 3013, cat: .geography, diff: .medium, q: "What country has the most natural lakes in the world?", a: ["Russia","United States","Finland","Canada"], c: 3),
        TriviaQ(id: 3014, cat: .geography, diff: .medium, q: "The Amazon River flows primarily through which country?", a: ["Colombia","Peru","Venezuela","Brazil"], c: 3),
        TriviaQ(id: 3015, cat: .geography, diff: .medium, q: "What is the capital of Brazil?", a: ["Rio de Janeiro","São Paulo","Salvador","Brasília"], c: 3),
        TriviaQ(id: 3016, cat: .geography, diff: .medium, q: "What is the name of the large lake on the border of Peru and Bolivia?", a: ["Lake Maracaibo","Lake Titicaca","Lake Nicaragua","Lake Poopo"], c: 1),
        TriviaQ(id: 3017, cat: .geography, diff: .medium, q: "Which country contains the most of the Amazon rainforest?", a: ["Bolivia","Peru","Colombia","Brazil"], c: 3),
        TriviaQ(id: 3018, cat: .geography, diff: .medium, q: "What is the capital of South Africa?", a: ["Cape Town","Johannesburg","Durban","Pretoria"], c: 3),
        TriviaQ(id: 3019, cat: .geography, diff: .medium, q: "What strait separates Europe from Africa?", a: ["Strait of Dover","Strait of Hormuz","Strait of Malacca","Strait of Gibraltar"], c: 3),
        TriviaQ(id: 3020, cat: .geography, diff: .medium, q: "What is the largest lake in Africa?", a: ["Lake Malawi","Lake Tanganyika","Lake Chad","Lake Victoria"], c: 3),
        TriviaQ(id: 3021, cat: .geography, diff: .hard, q: "What is the capital of Kazakhstan?", a: ["Almaty","Shymkent","Aktobe","Astana"], c: 3),
        TriviaQ(id: 3022, cat: .geography, diff: .hard, q: "What is the longest mountain range in the world?", a: ["Himalayas","Rocky Mountains","Andes","Alps"], c: 2),
        TriviaQ(id: 3023, cat: .geography, diff: .hard, q: "What is the deepest lake in the world?", a: ["Lake Tanganyika","Caspian Sea","Lake Superior","Lake Baikal"], c: 3),
        TriviaQ(id: 3024, cat: .geography, diff: .medium, q: "What European country is the Iberian Peninsula primarily composed of?", a: ["France and Spain","Portugal and Spain","Spain and Italy","Portugal and France"], c: 1),
        TriviaQ(id: 3025, cat: .geography, diff: .easy, q: "What is the capital of Germany?", a: ["Munich","Hamburg","Frankfurt","Berlin"], c: 3),
        TriviaQ(id: 3026, cat: .geography, diff: .medium, q: "What is the tallest mountain in Africa?", a: ["Mount Kenya","Ras Dashen","Kilimanjaro","Mount Meru"], c: 2),
        TriviaQ(id: 3027, cat: .geography, diff: .medium, q: "Which two countries share the longest international border?", a: ["USA and Russia","China and Russia","USA and Canada","Brazil and Bolivia"], c: 2),
        TriviaQ(id: 3028, cat: .geography, diff: .hard, q: "What is the name of the deepest point in the ocean?", a: ["Puerto Rico Trench","Java Trench","Mariana Trench","Philippine Trench"], c: 2),
        TriviaQ(id: 3029, cat: .geography, diff: .medium, q: "What is the capital of Argentina?", a: ["Santiago","Lima","Montevideo","Buenos Aires"], c: 3),
        TriviaQ(id: 3030, cat: .geography, diff: .medium, q: "The Maldives islands are located in which ocean?", a: ["Pacific","Atlantic","Arctic","Indian"], c: 3),
        TriviaQ(id: 3031, cat: .geography, diff: .easy, q: "What is the capital of Italy?", a: ["Milan","Florence","Naples","Rome"], c: 3),
        TriviaQ(id: 3032, cat: .geography, diff: .medium, q: "What U.S. state is the largest by area?", a: ["Texas","California","Montana","Alaska"], c: 3),
        TriviaQ(id: 3033, cat: .geography, diff: .hard, q: "What is the capital of Myanmar (Burma)?", a: ["Rangoon","Mandalay","Naypyidaw","Bago"], c: 2),
        TriviaQ(id: 3034, cat: .geography, diff: .easy, q: "What country is home to the Great Barrier Reef?", a: ["New Zealand","Philippines","Indonesia","Australia"], c: 3),
        TriviaQ(id: 3035, cat: .geography, diff: .medium, q: "What river flows through London?", a: ["Avon","Severn","Mersey","Thames"], c: 3),
        TriviaQ(id: 3036, cat: .geography, diff: .medium, q: "What is the capital of Saudi Arabia?", a: ["Jeddah","Mecca","Medina","Riyadh"], c: 3),
        TriviaQ(id: 3037, cat: .geography, diff: .hard, q: "The Atacama Desert is located in which country?", a: ["Argentina","Peru","Bolivia","Chile"], c: 3),
        TriviaQ(id: 3038, cat: .geography, diff: .medium, q: "What is the longest river in Europe?", a: ["Rhine","Danube","Don","Volga"], c: 3),
        TriviaQ(id: 3039, cat: .geography, diff: .easy, q: "What is the capital of China?", a: ["Shanghai","Hong Kong","Chengdu","Beijing"], c: 3),
        TriviaQ(id: 3040, cat: .geography, diff: .hard, q: "Which country has the most time zones?", a: ["Russia","United States","China","France"], c: 3),
        TriviaQ(id: 3041, cat: .geography, diff: .medium, q: "What is the capital of Egypt?", a: ["Alexandria","Luxor","Aswan","Cairo"], c: 3),
        TriviaQ(id: 3042, cat: .geography, diff: .medium, q: "In which ocean is the island of Madagascar located?", a: ["Atlantic","Pacific","Indian","Southern"], c: 2),
        TriviaQ(id: 3043, cat: .geography, diff: .easy, q: "What is the capital of Spain?", a: ["Barcelona","Seville","Valencia","Madrid"], c: 3),
        TriviaQ(id: 3044, cat: .geography, diff: .hard, q: "What is the name of the geographic region where three countries of Argentina, Brazil, and Paraguay meet?", a: ["Three Nations Corner","Triple Point","Triple Frontier","Southern Triangle"], c: 2),
        TriviaQ(id: 3045, cat: .geography, diff: .medium, q: "What is the name of the mountain range that separates Europe and Asia in Russia?", a: ["Caucasus","Urals","Altai","Sayan"], c: 1),
        TriviaQ(id: 3046, cat: .geography, diff: .easy, q: "What is the capital of Mexico?", a: ["Guadalajara","Monterrey","Puebla","Mexico City"], c: 3),
        TriviaQ(id: 3047, cat: .geography, diff: .medium, q: "What island country is located south of India?", a: ["Maldives","Madagascar","Sri Lanka","Comoros"], c: 2),
        TriviaQ(id: 3048, cat: .geography, diff: .hard, q: "What is the name of the world's largest archipelago nation?", a: ["Philippines","Japan","Indonesia","Malaysia"], c: 2),
        TriviaQ(id: 3049, cat: .geography, diff: .medium, q: "What is the capital of Turkey?", a: ["Istanbul","Izmir","Bursa","Ankara"], c: 3),
        TriviaQ(id: 3050, cat: .geography, diff: .hard, q: "Lake Titicaca sits at an elevation of approximately how many meters?", a: ["2,500m","3,300m","3,812m","4,100m"], c: 2),
    ]}

    // MARK: — Sports (4000–4079)
    private static var sports: [TriviaQ] {[
        TriviaQ(id: 4001, cat: .sports, diff: .easy, q: "How many players are on a standard soccer team on the field?", a: ["9","10","11","12"], c: 2),
        TriviaQ(id: 4002, cat: .sports, diff: .easy, q: "How many rings are on the Olympic flag?", a: ["4","5","6","7"], c: 1),
        TriviaQ(id: 4003, cat: .sports, diff: .easy, q: "In basketball, how many points is a standard field goal worth?", a: ["1","2","3","4"], c: 1),
        TriviaQ(id: 4004, cat: .sports, diff: .easy, q: "How many holes are in a standard golf course?", a: ["9","12","16","18"], c: 3),
        TriviaQ(id: 4005, cat: .sports, diff: .easy, q: "What sport is played at Wimbledon?", a: ["Golf","Cricket","Badminton","Tennis"], c: 3),
        TriviaQ(id: 4006, cat: .sports, diff: .easy, q: "How many players are on a baseball team on the field?", a: ["7","8","9","10"], c: 2),
        TriviaQ(id: 4007, cat: .sports, diff: .easy, q: "What country won the most gold medals in the 2020 Tokyo Olympics?", a: ["China","Russia","Great Britain","United States"], c: 3),
        TriviaQ(id: 4008, cat: .sports, diff: .easy, q: "In American football, how many points is a touchdown worth?", a: ["3","6","7","8"], c: 1),
        TriviaQ(id: 4009, cat: .sports, diff: .easy, q: "How many Grand Slam titles does the tennis term refer to?", a: ["2","3","4","5"], c: 2),
        TriviaQ(id: 4010, cat: .sports, diff: .easy, q: "What sport uses a puck?", a: ["Lacrosse","Field Hockey","Polo","Ice Hockey"], c: 3),
        TriviaQ(id: 4011, cat: .sports, diff: .medium, q: "Who holds the record for the most Grand Slam singles titles in men's tennis?", a: ["Roger Federer","Rafael Nadal","Pete Sampras","Novak Djokovic"], c: 3),
        TriviaQ(id: 4012, cat: .sports, diff: .medium, q: "What country has won the most FIFA World Cup titles?", a: ["Germany","Argentina","Italy","Brazil"], c: 3),
        TriviaQ(id: 4013, cat: .sports, diff: .medium, q: "Who scored the most points in NBA history?", a: ["Kobe Bryant","LeBron James","Kareem Abdul-Jabbar","Wilt Chamberlain"], c: 1),
        TriviaQ(id: 4014, cat: .sports, diff: .medium, q: "What is the diameter of a standard basketball hoop in inches?", a: ["16 inches","18 inches","20 inches","22 inches"], c: 1),
        TriviaQ(id: 4015, cat: .sports, diff: .medium, q: "In what year were women first allowed to compete in the Olympic Games?", a: ["1896","1900","1912","1920"], c: 1),
        TriviaQ(id: 4016, cat: .sports, diff: .medium, q: "What baseball player hit 73 home runs in a single season?", a: ["Mark McGwire","Sammy Sosa","Mickey Mantle","Barry Bonds"], c: 3),
        TriviaQ(id: 4017, cat: .sports, diff: .medium, q: "In which city is the Tour de France traditionally held?", a: ["Nice","Lyon","Bordeaux","Paris"], c: 3),
        TriviaQ(id: 4018, cat: .sports, diff: .medium, q: "What country invented basketball?", a: ["USA","Canada","UK","Brazil"], c: 0),
        TriviaQ(id: 4019, cat: .sports, diff: .medium, q: "Who holds the record for the most home runs in MLB history?", a: ["Hank Aaron","Babe Ruth","Willie Mays","Barry Bonds"], c: 3),
        TriviaQ(id: 4020, cat: .sports, diff: .medium, q: "In swimming, how many lengths make up a 100m race in a standard 50m pool?", a: ["1","2","4","8"], c: 1),
        TriviaQ(id: 4021, cat: .sports, diff: .hard, q: "What is the maximum break (highest possible score) in a single snooker frame?", a: ["127","147","155","161"], c: 1),
        TriviaQ(id: 4022, cat: .sports, diff: .hard, q: "How many calories does a marathoner burn on average?", a: ["1,500","2,600","3,200","4,500"], c: 1),
        TriviaQ(id: 4023, cat: .sports, diff: .hard, q: "Who was the first person to run a sub-4-minute mile?", a: ["Jim Ryun","Sebastian Coe","Arne Andersson","Roger Bannister"], c: 3),
        TriviaQ(id: 4024, cat: .sports, diff: .medium, q: "How many sets does a Grand Slam men's tennis final go up to?", a: ["3","4","5","6"], c: 2),
        TriviaQ(id: 4025, cat: .sports, diff: .easy, q: "What sport features a shuttlecock?", a: ["Squash","Racquetball","Badminton","Pickleball"], c: 2),
        TriviaQ(id: 4026, cat: .sports, diff: .medium, q: "Which NFL team has won the most Super Bowls?", a: ["San Francisco 49ers","Dallas Cowboys","Pittsburgh Steelers","New England Patriots"], c: 2),
        TriviaQ(id: 4027, cat: .sports, diff: .hard, q: "What is the name of the trophy awarded to the NHL champion?", a: ["Presidents' Trophy","Conn Smythe Trophy","Vezina Trophy","Stanley Cup"], c: 3),
        TriviaQ(id: 4028, cat: .sports, diff: .medium, q: "How many outs are there in a standard baseball inning?", a: ["3","4","6","9"], c: 2),
        TriviaQ(id: 4029, cat: .sports, diff: .easy, q: "In what country did the Olympic Games originate?", a: ["Rome","Egypt","Persia","Greece"], c: 3),
        TriviaQ(id: 4030, cat: .sports, diff: .hard, q: "What boxer was known as 'The Greatest' and 'The Louisville Lip'?", a: ["Joe Frazier","George Foreman","Sugar Ray Leonard","Muhammad Ali"], c: 3),
        TriviaQ(id: 4031, cat: .sports, diff: .medium, q: "How many yards is an American football field from end zone to end zone?", a: ["80","90","100","110"], c: 2),
        TriviaQ(id: 4032, cat: .sports, diff: .easy, q: "In tennis, what does 'love' mean?", a: ["Win","40 points","zero points","deuce"], c: 2),
        TriviaQ(id: 4033, cat: .sports, diff: .medium, q: "What is the shortest swim event at the Olympics?", a: ["50m freestyle","100m freestyle","50m butterfly","100m backstroke"], c: 0),
        TriviaQ(id: 4034, cat: .sports, diff: .hard, q: "Who holds the Olympic record for most gold medals in a single Games?", a: ["Jesse Owens","Carl Lewis","Larisa Latynina","Michael Phelps"], c: 3),
        TriviaQ(id: 4035, cat: .sports, diff: .medium, q: "What country has won the most Olympic gold medals in history?", a: ["Soviet Union","China","Great Britain","United States"], c: 3),
        TriviaQ(id: 4036, cat: .sports, diff: .easy, q: "How many points is a three-pointer worth in basketball?", a: ["2","3","4","5"], c: 1),
        TriviaQ(id: 4037, cat: .sports, diff: .medium, q: "In cricket, what is the maximum score for a single delivery?", a: ["4","5","6","7"], c: 2),
        TriviaQ(id: 4038, cat: .sports, diff: .hard, q: "What was Usain Bolt's world record time in the 100m sprint?", a: ["9.69","9.72","9.58","9.63"], c: 2),
        TriviaQ(id: 4039, cat: .sports, diff: .medium, q: "In which city is the Masters golf tournament held each year?", a: ["Augusta, Georgia","Pebble Beach, California","St. Andrews, Scotland","Sawgrass, Florida"], c: 0),
        TriviaQ(id: 4040, cat: .sports, diff: .easy, q: "How long is a marathon race?", a: ["25.2 miles","26.2 miles","27.2 miles","28.2 miles"], c: 1),
        TriviaQ(id: 4041, cat: .sports, diff: .medium, q: "How many players are on a volleyball team?", a: ["5","6","7","8"], c: 1),
        TriviaQ(id: 4042, cat: .sports, diff: .hard, q: "What is the average speed of a Formula 1 car during a race?", a: ["150 mph","200 mph","250 mph","300 mph"], c: 1),
        TriviaQ(id: 4043, cat: .sports, diff: .medium, q: "What sport is the Kentucky Derby associated with?", a: ["Dog racing","Harness racing","Horse racing","Greyhound racing"], c: 2),
        TriviaQ(id: 4044, cat: .sports, diff: .easy, q: "How many periods are in an NHL hockey game?", a: ["2","3","4","5"], c: 1),
        TriviaQ(id: 4045, cat: .sports, diff: .medium, q: "What country hosted the 1936 Summer Olympic Games?", a: ["Italy","France","England","Germany"], c: 3),
        TriviaQ(id: 4046, cat: .sports, diff: .hard, q: "Who won the first FIFA World Cup in 1930?", a: ["Argentina","Brazil","Uruguay","USA"], c: 2),
        TriviaQ(id: 4047, cat: .sports, diff: .easy, q: "How many players are on a basketball team on the court?", a: ["4","5","6","7"], c: 1),
        TriviaQ(id: 4048, cat: .sports, diff: .medium, q: "What is the name of the annual American football championship game?", a: ["Rose Bowl","Pro Bowl","World Bowl","Super Bowl"], c: 3),
        TriviaQ(id: 4049, cat: .sports, diff: .hard, q: "Which sprinter won 4 gold medals at the 1936 Berlin Olympics?", a: ["Jim Thorpe","Carl Lewis","Jesse Owens","Rafer Johnson"], c: 2),
        TriviaQ(id: 4050, cat: .sports, diff: .medium, q: "In golf, what is the term for one under par on a hole?", a: ["Eagle","Birdie","Bogey","Albatross"], c: 1),
    ]}

    // MARK: — Movies (5000–5079)
    private static var movies: [TriviaQ] {[
        TriviaQ(id: 5001, cat: .movies, diff: .easy, q: "What film won the first Academy Award for Best Picture?", a: ["All Quiet on the Western Front","Wings","Casablanca","Gone with the Wind"], c: 1),
        TriviaQ(id: 5002, cat: .movies, diff: .easy, q: "Who directed the film 'Schindler's List'?", a: ["Martin Scorsese","Francis Ford Coppola","Stanley Kubrick","Steven Spielberg"], c: 3),
        TriviaQ(id: 5003, cat: .movies, diff: .easy, q: "What 1997 film starred Leonardo DiCaprio and Kate Winslet?", a: ["Romeo + Juliet","The Beach","Titanic","Gangs of New York"], c: 2),
        TriviaQ(id: 5004, cat: .movies, diff: .easy, q: "Which actor played Iron Man in the Marvel Cinematic Universe?", a: ["Chris Evans","Chris Hemsworth","Robert Downey Jr.","Mark Ruffalo"], c: 2),
        TriviaQ(id: 5005, cat: .movies, diff: .easy, q: "What is the highest-grossing film of all time (not adjusted for inflation)?", a: ["Titanic","Star Wars: The Force Awakens","Avengers: Endgame","Avatar"], c: 3),
        TriviaQ(id: 5006, cat: .movies, diff: .easy, q: "Who played Forrest Gump in the 1994 film?", a: ["Kevin Costner","John Travolta","Tom Hanks","Robin Williams"], c: 2),
        TriviaQ(id: 5007, cat: .movies, diff: .easy, q: "What film features the line 'May the Force be with you'?", a: ["Star Trek","Flash Gordon","Dune","Star Wars"], c: 3),
        TriviaQ(id: 5008, cat: .movies, diff: .easy, q: "Who directed the 'Lord of the Rings' trilogy?", a: ["James Cameron","George Lucas","Peter Jackson","Ridley Scott"], c: 2),
        TriviaQ(id: 5009, cat: .movies, diff: .easy, q: "What animated film features the song 'Let It Go'?", a: ["Moana","Brave","Tangled","Frozen"], c: 3),
        TriviaQ(id: 5010, cat: .movies, diff: .easy, q: "Which film won the Oscar for Best Picture in 2020?", a: ["1917","Joker","The Irishman","Parasite"], c: 3),
        TriviaQ(id: 5011, cat: .movies, diff: .medium, q: "Who played the Joker in the 2019 film 'Joker'?", a: ["Heath Ledger","Jack Nicholson","Jared Leto","Joaquin Phoenix"], c: 3),
        TriviaQ(id: 5012, cat: .movies, diff: .medium, q: "What Pixar film is set in the Scottish Highlands?", a: ["Up","Cars","Brave","Ratatouille"], c: 2),
        TriviaQ(id: 5013, cat: .movies, diff: .medium, q: "What film starred Marlon Brando as Don Vito Corleone?", a: ["Scarface","Goodfellas","Casino","The Godfather"], c: 3),
        TriviaQ(id: 5014, cat: .movies, diff: .medium, q: "Who directed 'Pulp Fiction'?", a: ["Spike Lee","David Fincher","Joel Coen","Quentin Tarantino"], c: 3),
        TriviaQ(id: 5015, cat: .movies, diff: .medium, q: "What year was the original 'Star Wars' film released?", a: ["1975","1977","1979","1981"], c: 1),
        TriviaQ(id: 5016, cat: .movies, diff: .medium, q: "Which actress has won the most Academy Awards for acting?", a: ["Meryl Streep","Katharine Hepburn","Bette Davis","Cate Blanchett"], c: 1),
        TriviaQ(id: 5017, cat: .movies, diff: .medium, q: "What is the name of the fictional country in 'Black Panther'?", a: ["Genosha","Sokovia","Wakanda","Latveria"], c: 2),
        TriviaQ(id: 5018, cat: .movies, diff: .medium, q: "Who directed '2001: A Space Odyssey'?", a: ["Ridley Scott","Francis Ford Coppola","Steven Spielberg","Stanley Kubrick"], c: 3),
        TriviaQ(id: 5019, cat: .movies, diff: .medium, q: "What character does Harrison Ford play in the 'Indiana Jones' franchise?", a: ["Jack Ryan","Han Solo","Rick Deckard","Indiana Jones"], c: 3),
        TriviaQ(id: 5020, cat: .movies, diff: .medium, q: "Which director made 'Inception' and 'The Dark Knight'?", a: ["David Fincher","Denis Villeneuve","Zack Snyder","Christopher Nolan"], c: 3),
        TriviaQ(id: 5021, cat: .movies, diff: .hard, q: "What film became the first non-English language film to win the Oscar for Best Picture?", a: ["Roma","Life Is Beautiful","Cinema Paradiso","Parasite"], c: 3),
        TriviaQ(id: 5022, cat: .movies, diff: .hard, q: "Who won the first Academy Award for Best Actor?", a: ["Lionel Barrymore","George Arliss","Charles Chaplin","Emil Jannings"], c: 3),
        TriviaQ(id: 5023, cat: .movies, diff: .hard, q: "What 1960 Alfred Hitchcock film features the famous shower scene?", a: ["Vertigo","Rear Window","The Birds","Psycho"], c: 3),
        TriviaQ(id: 5024, cat: .movies, diff: .medium, q: "What actor played James Bond most times?", a: ["Daniel Craig","Pierce Brosnan","Sean Connery","Roger Moore"], c: 3),
        TriviaQ(id: 5025, cat: .movies, diff: .easy, q: "Which Disney film features the character Simba?", a: ["Bambi","Jungle Book","Lion King","Tarzan"], c: 2),
        TriviaQ(id: 5026, cat: .movies, diff: .medium, q: "Which 1990s film featured the quote 'You can't handle the truth!'?", a: ["Braveheart","A Few Good Men","The Firm","JFK"], c: 1),
        TriviaQ(id: 5027, cat: .movies, diff: .hard, q: "What is the name of the director who made 'Citizen Kane'?", a: ["John Ford","Howard Hawks","Frank Capra","Orson Welles"], c: 3),
        TriviaQ(id: 5028, cat: .movies, diff: .medium, q: "What film features a tornado in Kansas and a visit to the land of Oz?", a: ["Return to Oz","The Wiz","Oz the Great and Powerful","The Wizard of Oz"], c: 3),
        TriviaQ(id: 5029, cat: .movies, diff: .medium, q: "Who played the lead role in 'The Silence of the Lambs'?", a: ["Meryl Streep","Glenn Close","Sigourney Weaver","Jodie Foster"], c: 3),
        TriviaQ(id: 5030, cat: .movies, diff: .hard, q: "What film directed by Federico Fellini is considered a classic of Italian neorealism?", a: ["8½","Amarcord","La Dolce Vita","La Strada"], c: 3),
        TriviaQ(id: 5031, cat: .movies, diff: .easy, q: "Who plays Harry Potter in the film series?", a: ["Rupert Grint","Tom Felton","Daniel Radcliffe","Robert Pattinson"], c: 2),
        TriviaQ(id: 5032, cat: .movies, diff: .easy, q: "What company made the 'Toy Story' films?", a: ["DreamWorks","Pixar","Disney","Studio Ghibli"], c: 1),
        TriviaQ(id: 5033, cat: .movies, diff: .medium, q: "In 'The Matrix', what color pill does Neo take?", a: ["Blue","Green","Red","White"], c: 2),
        TriviaQ(id: 5034, cat: .movies, diff: .medium, q: "Who directed 'Jurassic Park'?", a: ["James Cameron","Michael Bay","George Lucas","Steven Spielberg"], c: 3),
        TriviaQ(id: 5035, cat: .movies, diff: .hard, q: "What year did the movie 'Casablanca' premiere?", a: ["1940","1941","1942","1943"], c: 2),
        TriviaQ(id: 5036, cat: .movies, diff: .medium, q: "What actor has appeared in the most films over his career?", a: ["Samuel L. Jackson","Christopher Lee","John Carradine","Mickey Rooney"], c: 1),
        TriviaQ(id: 5037, cat: .movies, diff: .easy, q: "What film features the music of John Williams and 'The Imperial March'?", a: ["Indiana Jones","Superman","Star Wars","Jaws"], c: 2),
        TriviaQ(id: 5038, cat: .movies, diff: .medium, q: "Who played Tony Stark / Iron Man before the MCU era on screen?", a: ["Robert Downey Jr.","Val Kilmer","Tom Selleck","No actor — first Iron Man was MCU"], c: 3),
        TriviaQ(id: 5039, cat: .movies, diff: .medium, q: "Which 1986 film features Tom Cruise as a naval fighter pilot?", a: ["Top Gun","Cocktail","Born on the Fourth of July","The Color of Money"], c: 0),
        TriviaQ(id: 5040, cat: .movies, diff: .hard, q: "Who was the first actor to receive $1 million for a film role?", a: ["Cary Grant","Clark Gable","Jimmy Stewart","Marlon Brando"], c: 3),
    ]}

    // MARK: — Music (6000–6079)
    private static var music: [TriviaQ] {[
        TriviaQ(id: 6001, cat: .music, diff: .easy, q: "Which band recorded 'Bohemian Rhapsody'?", a: ["Led Zeppelin","The Rolling Stones","The Who","Queen"], c: 3),
        TriviaQ(id: 6002, cat: .music, diff: .easy, q: "Who is known as the 'King of Pop'?", a: ["Prince","Elvis Presley","David Bowie","Michael Jackson"], c: 3),
        TriviaQ(id: 6003, cat: .music, diff: .easy, q: "What band were John Lennon and Paul McCartney members of?", a: ["The Rolling Stones","The Kinks","The Who","The Beatles"], c: 3),
        TriviaQ(id: 6004, cat: .music, diff: .easy, q: "What instrument does a violinist play?", a: ["Viola","Violin","Cello","Guitar"], c: 1),
        TriviaQ(id: 6005, cat: .music, diff: .easy, q: "What famous rock guitarist was known as 'Slowhand'?", a: ["Jimmy Page","Carlos Santana","Jimi Hendrix","Eric Clapton"], c: 3),
        TriviaQ(id: 6006, cat: .music, diff: .easy, q: "What pop star released the album 'Thriller' in 1982?", a: ["Prince","Madonna","Michael Jackson","Whitney Houston"], c: 2),
        TriviaQ(id: 6007, cat: .music, diff: .easy, q: "What is the highest male singing voice?", a: ["Bass","Baritone","Tenor","Countertenor"], c: 2),
        TriviaQ(id: 6008, cat: .music, diff: .easy, q: "Who sang 'Rolling in the Deep'?", a: ["Beyoncé","Rihanna","Adele","Taylor Swift"], c: 2),
        TriviaQ(id: 6009, cat: .music, diff: .easy, q: "What number of strings does a standard guitar have?", a: ["4","5","6","7"], c: 2),
        TriviaQ(id: 6010, cat: .music, diff: .easy, q: "What country is known for the musical genre 'Tango'?", a: ["Brazil","Chile","Uruguay","Argentina"], c: 3),
        TriviaQ(id: 6011, cat: .music, diff: .medium, q: "What was the name of the Beatles' last studio album?", a: ["White Album","Yellow Submarine","Let It Be","Abbey Road"], c: 2),
        TriviaQ(id: 6012, cat: .music, diff: .medium, q: "Who composed 'The Four Seasons'?", a: ["Bach","Handel","Vivaldi","Mozart"], c: 2),
        TriviaQ(id: 6013, cat: .music, diff: .medium, q: "What rapper's real name is Aubrey Drake Graham?", a: ["Jay-Z","Kendrick Lamar","Drake","J. Cole"], c: 2),
        TriviaQ(id: 6014, cat: .music, diff: .medium, q: "What music genre did artists like Robert Johnson and Muddy Waters pioneer?", a: ["Jazz","Country","Blues","Soul"], c: 2),
        TriviaQ(id: 6015, cat: .music, diff: .medium, q: "Which country does ABBA come from?", a: ["Norway","Denmark","Finland","Sweden"], c: 3),
        TriviaQ(id: 6016, cat: .music, diff: .medium, q: "Who is the best-selling female music artist of all time?", a: ["Celine Dion","Rihanna","Taylor Swift","Madonna"], c: 3),
        TriviaQ(id: 6017, cat: .music, diff: .medium, q: "What instrument does Yo-Yo Ma play?", a: ["Violin","Viola","Piano","Cello"], c: 3),
        TriviaQ(id: 6018, cat: .music, diff: .medium, q: "What is the name of Taylor Swift's debut album?", a: ["Fearless","Speak Now","Taylor Swift","Red"], c: 2),
        TriviaQ(id: 6019, cat: .music, diff: .medium, q: "What rock band's members include Dave Grohl, Krist Novoselic, and Kurt Cobain?", a: ["Pearl Jam","Soundgarden","Alice in Chains","Nirvana"], c: 3),
        TriviaQ(id: 6020, cat: .music, diff: .medium, q: "Which composer was deaf when he composed his 9th Symphony?", a: ["Mozart","Brahms","Beethoven","Chopin"], c: 2),
        TriviaQ(id: 6021, cat: .music, diff: .hard, q: "What is the name of the technique in music where a single vocal sound is held as other voices change?", a: ["Counterpoint","Ostinato","Pedal point","Fugue"], c: 2),
        TriviaQ(id: 6022, cat: .music, diff: .hard, q: "What key is 'Für Elise' by Beethoven written in?", a: ["C major","G major","A minor","E minor"], c: 2),
        TriviaQ(id: 6023, cat: .music, diff: .hard, q: "Which composer wrote 'The Rite of Spring'?", a: ["Shostakovich","Prokofiev","Bartók","Stravinsky"], c: 3),
        TriviaQ(id: 6024, cat: .music, diff: .medium, q: "What genre of music is Bob Marley most associated with?", a: ["Calypso","Ska","Dancehall","Reggae"], c: 3),
        TriviaQ(id: 6025, cat: .music, diff: .easy, q: "What pop diva is known as 'Queen Bey'?", a: ["Rihanna","Mariah Carey","Ariana Grande","Beyoncé"], c: 3),
        TriviaQ(id: 6026, cat: .music, diff: .medium, q: "What music streaming platform was founded in Sweden in 2006?", a: ["Apple Music","Tidal","Pandora","Spotify"], c: 3),
        TriviaQ(id: 6027, cat: .music, diff: .hard, q: "What composer wrote 'Also Sprach Zarathustra', famously used in '2001: A Space Odyssey'?", a: ["Wagner","Mahler","Strauss","Liszt"], c: 2),
        TriviaQ(id: 6028, cat: .music, diff: .medium, q: "What year did Elvis Presley die?", a: ["1975","1976","1977","1979"], c: 2),
        TriviaQ(id: 6029, cat: .music, diff: .easy, q: "What is the name of Eminem's rap alter ego?", a: ["Proof","Slim Shady","Marshall","D12"], c: 1),
        TriviaQ(id: 6030, cat: .music, diff: .medium, q: "What was the first music video played on MTV when it launched in 1981?", a: ["Video Killed the Radio Star","Thriller","Bohemian Rhapsody","Like a Virgin"], c: 0),
        TriviaQ(id: 6031, cat: .music, diff: .hard, q: "Who composed the opera 'La Traviata'?", a: ["Puccini","Rossini","Bellini","Verdi"], c: 3),
        TriviaQ(id: 6032, cat: .music, diff: .medium, q: "What rock band was Mick Jagger the lead singer of?", a: ["Led Zeppelin","The Who","The Kinks","The Rolling Stones"], c: 3),
        TriviaQ(id: 6033, cat: .music, diff: .medium, q: "What is the tempo marking 'Presto' equivalent to in beats per minute?", a: ["60–80 BPM","80–120 BPM","120–168 BPM","168–200 BPM"], c: 3),
        TriviaQ(id: 6034, cat: .music, diff: .easy, q: "What female artist released the album '1989'?", a: ["Katy Perry","Adele","Selena Gomez","Taylor Swift"], c: 3),
        TriviaQ(id: 6035, cat: .music, diff: .hard, q: "What jazz musician is known as 'Trane' and played the saxophone?", a: ["Miles Davis","Duke Ellington","Charlie Parker","John Coltrane"], c: 3),
        TriviaQ(id: 6036, cat: .music, diff: .medium, q: "What hip-hop duo released 'The Chronic' in 1992?", a: ["NWA","Snoop Dogg and Warren G","Dr. Dre and Eazy-E","Dr. Dre, solo artist"], c: 3),
        TriviaQ(id: 6037, cat: .music, diff: .easy, q: "What band sang 'Hotel California'?", a: ["Fleetwood Mac","The Eagles","Chicago","Steely Dan"], c: 1),
        TriviaQ(id: 6038, cat: .music, diff: .medium, q: "What instrument did Jimi Hendrix play?", a: ["Bass","Drums","Piano","Guitar"], c: 3),
        TriviaQ(id: 6039, cat: .music, diff: .hard, q: "What is the name for the Italian musical term meaning gradually getting softer?", a: ["Decrescendo","Rallentando","Ritenuto","Diminuendo"], c: 0),
        TriviaQ(id: 6040, cat: .music, diff: .medium, q: "What is the name of the most-streamed song of all time on Spotify?", a: ["Shape of You","Despacito","Blinding Lights","Dance Monkey"], c: 2),
    ]}

    // MARK: — Literature (7000–7059)
    private static var literature: [TriviaQ] {[
        TriviaQ(id: 7001, cat: .literature, diff: .easy, q: "Who wrote 'Romeo and Juliet'?", a: ["Christopher Marlowe","Ben Jonson","John Milton","William Shakespeare"], c: 3),
        TriviaQ(id: 7002, cat: .literature, diff: .easy, q: "Who wrote 'The Great Gatsby'?", a: ["Ernest Hemingway","John Steinbeck","F. Scott Fitzgerald","William Faulkner"], c: 2),
        TriviaQ(id: 7003, cat: .literature, diff: .easy, q: "In what novel does the character Sherlock Holmes appear?", a: ["The Mystery of Edwin Drood","The Woman in White","The Adventures of Sherlock Holmes","The Moonstone"], c: 2),
        TriviaQ(id: 7004, cat: .literature, diff: .easy, q: "Who wrote '1984'?", a: ["Aldous Huxley","Ray Bradbury","H.G. Wells","George Orwell"], c: 3),
        TriviaQ(id: 7005, cat: .literature, diff: .easy, q: "What novel features the characters Frodo Baggins and Gandalf?", a: ["The Chronicles of Narnia","A Wizard of Earthsea","The Wheel of Time","The Lord of the Rings"], c: 3),
        TriviaQ(id: 7006, cat: .literature, diff: .easy, q: "Who wrote 'Pride and Prejudice'?", a: ["Charlotte Brontë","Emily Brontë","George Eliot","Jane Austen"], c: 3),
        TriviaQ(id: 7007, cat: .literature, diff: .easy, q: "What is the name of Harry Potter's owl?", a: ["Crookshanks","Scabbers","Fang","Hedwig"], c: 3),
        TriviaQ(id: 7008, cat: .literature, diff: .easy, q: "Who wrote 'To Kill a Mockingbird'?", a: ["Carson McCullers","Flannery O'Connor","Zora Neale Hurston","Harper Lee"], c: 3),
        TriviaQ(id: 7009, cat: .literature, diff: .medium, q: "What author wrote the 'Chronicles of Narnia' series?", a: ["J.R.R. Tolkien","Lloyd Alexander","Ursula K. Le Guin","C.S. Lewis"], c: 3),
        TriviaQ(id: 7010, cat: .literature, diff: .medium, q: "In which city does the novel 'Crime and Punishment' take place?", a: ["Moscow","Berlin","Warsaw","St. Petersburg"], c: 3),
        TriviaQ(id: 7011, cat: .literature, diff: .medium, q: "Who wrote 'Don Quixote'?", a: ["Dante Alighieri","Miguel de Cervantes","Lope de Vega","Pedro Calderón"], c: 1),
        TriviaQ(id: 7012, cat: .literature, diff: .medium, q: "What is the name of the whale in 'Moby-Dick'?", a: ["Moby Dick","The White Whale","Leviathan","No name — it's just 'the whale'"], c: 0),
        TriviaQ(id: 7013, cat: .literature, diff: .medium, q: "Who wrote 'The Catcher in the Rye'?", a: ["John Updike","Philip Roth","Saul Bellow","J.D. Salinger"], c: 3),
        TriviaQ(id: 7014, cat: .literature, diff: .medium, q: "What Shakespeare play features the character Iago?", a: ["Macbeth","King Lear","Hamlet","Othello"], c: 3),
        TriviaQ(id: 7015, cat: .literature, diff: .medium, q: "What poet wrote 'The Waste Land' in 1922?", a: ["Ezra Pound","W.B. Yeats","Dylan Thomas","T.S. Eliot"], c: 3),
        TriviaQ(id: 7016, cat: .literature, diff: .medium, q: "Who wrote 'One Hundred Years of Solitude'?", a: ["Mario Vargas Llosa","Pablo Neruda","Jorge Luis Borges","Gabriel García Márquez"], c: 3),
        TriviaQ(id: 7017, cat: .literature, diff: .hard, q: "What is the name of the detective in Agatha Christie's most famous series?", a: ["Miss Marple","Superintendent Battle","Hercule Poirot","Tommy Beresford"], c: 2),
        TriviaQ(id: 7018, cat: .literature, diff: .hard, q: "Who wrote 'Ulysses', considered one of the most important works of modernist literature?", a: ["Samuel Beckett","Dylan Thomas","Virginia Woolf","James Joyce"], c: 3),
        TriviaQ(id: 7019, cat: .literature, diff: .hard, q: "What work by Dante Alighieri describes a journey through the afterlife?", a: ["The Decameron","La Vita Nuova","De Monarchia","The Divine Comedy"], c: 3),
        TriviaQ(id: 7020, cat: .literature, diff: .easy, q: "Who wrote 'Harry Potter and the Sorcerer's Stone'?", a: ["Roald Dahl","C.S. Lewis","Philip Pullman","J.K. Rowling"], c: 3),
        TriviaQ(id: 7021, cat: .literature, diff: .medium, q: "What novel by Aldous Huxley depicts a dystopian future society?", a: ["We","Brave New World","The Time Machine","Animal Farm"], c: 1),
        TriviaQ(id: 7022, cat: .literature, diff: .medium, q: "What is the name of the author who wrote 'Of Mice and Men'?", a: ["William Faulkner","Sinclair Lewis","Theodore Dreiser","John Steinbeck"], c: 3),
        TriviaQ(id: 7023, cat: .literature, diff: .hard, q: "What Russian author wrote 'War and Peace'?", a: ["Fyodor Dostoevsky","Ivan Turgenev","Anton Chekhov","Leo Tolstoy"], c: 3),
        TriviaQ(id: 7024, cat: .literature, diff: .medium, q: "What is the setting of 'The Grapes of Wrath' by John Steinbeck?", a: ["Great Depression-era Oklahoma to California","Post-War New York","Mississippi in the 1920s","Chicago during Prohibition"], c: 0),
        TriviaQ(id: 7025, cat: .literature, diff: .hard, q: "Who wrote the epic poem 'Paradise Lost'?", a: ["Geoffrey Chaucer","Edmund Spenser","John Dryden","John Milton"], c: 3),
        TriviaQ(id: 7026, cat: .literature, diff: .medium, q: "What is the first line of 'A Tale of Two Cities' by Charles Dickens?", a: ["Call me Ishmael.","It was the best of times, it was the worst of times.","It is a truth universally acknowledged...","Many years later, as he faced the firing squad..."], c: 1),
        TriviaQ(id: 7027, cat: .literature, diff: .easy, q: "Who wrote 'Alice's Adventures in Wonderland'?", a: ["H.G. Wells","Oscar Wilde","Lewis Carroll","Robert Louis Stevenson"], c: 2),
        TriviaQ(id: 7028, cat: .literature, diff: .hard, q: "What Homer epic poem follows Odysseus on his journey home from Troy?", a: ["The Aeneid","The Iliad","The Odyssey","Works and Days"], c: 2),
        TriviaQ(id: 7029, cat: .literature, diff: .medium, q: "What French author wrote 'Les Misérables'?", a: ["Émile Zola","Alexandre Dumas","Gustave Flaubert","Victor Hugo"], c: 3),
        TriviaQ(id: 7030, cat: .literature, diff: .easy, q: "Who created the fictional character James Bond?", a: ["John le Carré","Graham Greene","Frederick Forsyth","Ian Fleming"], c: 3),
        TriviaQ(id: 7031, cat: .literature, diff: .hard, q: "What style of poetry consists of three lines with 5-7-5 syllables?", a: ["Haiku","Tanka","Renga","Senryū"], c: 0),
        TriviaQ(id: 7032, cat: .literature, diff: .medium, q: "What is the subtitle of Mary Shelley's 'Frankenstein'?", a: ["A Gothic Horror","The Monster Speaks","The Modern Prometheus","The Creation"], c: 2),
        TriviaQ(id: 7033, cat: .literature, diff: .hard, q: "What Irish writer authored 'The Importance of Being Earnest'?", a: ["George Bernard Shaw","W.B. Yeats","Samuel Beckett","Oscar Wilde"], c: 3),
        TriviaQ(id: 7034, cat: .literature, diff: .medium, q: "What is the name of the narrator in 'Moby-Dick'?", a: ["Ahab","Queequeg","Starbuck","Ishmael"], c: 3),
        TriviaQ(id: 7035, cat: .literature, diff: .medium, q: "Who wrote 'The Old Man and the Sea'?", a: ["F. Scott Fitzgerald","William Faulkner","John Steinbeck","Ernest Hemingway"], c: 3),
        TriviaQ(id: 7036, cat: .literature, diff: .easy, q: "What is the name of the dragon in 'The Hobbit'?", a: ["Glaurung","Ancalagon","Smaug","Scatha"], c: 2),
        TriviaQ(id: 7037, cat: .literature, diff: .hard, q: "Which Czech author wrote 'The Trial' and 'The Metamorphosis'?", a: ["Milan Kundera","Jaroslav Hašek","Franz Kafka","Bohumil Hrabal"], c: 2),
        TriviaQ(id: 7038, cat: .literature, diff: .medium, q: "Who wrote 'Brave New World'?", a: ["George Orwell","Ray Bradbury","Arthur C. Clarke","Aldous Huxley"], c: 3),
        TriviaQ(id: 7039, cat: .literature, diff: .hard, q: "Who was the first woman to win the Nobel Prize for Literature?", a: ["Selma Lagerlöf","Pearl Buck","Nelly Sachs","Sigrid Undset"], c: 0),
        TriviaQ(id: 7040, cat: .literature, diff: .easy, q: "What author wrote the 'Discworld' series of fantasy novels?", a: ["Neil Gaiman","Robert Jordan","Terry Brooks","Terry Pratchett"], c: 3),
    ]}

    // MARK: — Technology (8000–8079)
    private static var technology: [TriviaQ] {[
        TriviaQ(id: 8001, cat: .technology, diff: .easy, q: "What does 'WWW' stand for?", a: ["Wide World Website","World Wide Web","Web World Wire","World Web Wire"], c: 1),
        TriviaQ(id: 8002, cat: .technology, diff: .easy, q: "Who co-founded Apple with Steve Jobs?", a: ["Bill Gates","Paul Allen","Steve Wozniak","Michael Dell"], c: 2),
        TriviaQ(id: 8003, cat: .technology, diff: .easy, q: "What does 'CPU' stand for?", a: ["Computer Processing Unit","Central Processing Unit","Core Processing Unit","Central Power Unit"], c: 1),
        TriviaQ(id: 8004, cat: .technology, diff: .easy, q: "What company created the Android operating system?", a: ["Apple","Microsoft","Amazon","Google"], c: 3),
        TriviaQ(id: 8005, cat: .technology, diff: .easy, q: "What does 'USB' stand for?", a: ["Universal Serial Bus","Unified System Board","Universal System Base","United Serial Bus"], c: 0),
        TriviaQ(id: 8006, cat: .technology, diff: .easy, q: "Who founded Microsoft?", a: ["Steve Jobs and Steve Wozniak","Larry Page and Sergey Brin","Bill Gates and Paul Allen","Mark Zuckerberg and Eduardo Saverin"], c: 2),
        TriviaQ(id: 8007, cat: .technology, diff: .easy, q: "What does 'HTML' stand for?", a: ["HyperText Machine Language","HyperTransfer Markup Language","HyperText Markup Language","HighText Markup Language"], c: 2),
        TriviaQ(id: 8008, cat: .technology, diff: .easy, q: "What social media platform uses the hashtag '#'?", a: ["Facebook","Instagram","Twitter/X","TikTok"], c: 2),
        TriviaQ(id: 8009, cat: .technology, diff: .easy, q: "What does 'AI' stand for in technology?", a: ["Automated Intelligence","Artificial Intelligence","Advanced Interface","Algorithmic Intelligence"], c: 1),
        TriviaQ(id: 8010, cat: .technology, diff: .easy, q: "What company makes the iPhone?", a: ["Samsung","Google","Microsoft","Apple"], c: 3),
        TriviaQ(id: 8011, cat: .technology, diff: .medium, q: "What programming language was developed by Guido van Rossum?", a: ["Java","Ruby","JavaScript","Python"], c: 3),
        TriviaQ(id: 8012, cat: .technology, diff: .medium, q: "What year was the internet's World Wide Web invented?", a: ["1981","1985","1989","1993"], c: 2),
        TriviaQ(id: 8013, cat: .technology, diff: .medium, q: "What does 'RAM' stand for?", a: ["Read Access Memory","Rapid Application Memory","Random Access Memory","Readable Array Memory"], c: 2),
        TriviaQ(id: 8014, cat: .technology, diff: .medium, q: "What was the first programmable electronic computer?", a: ["UNIVAC","ENIAC","Mark I","Colossus"], c: 1),
        TriviaQ(id: 8015, cat: .technology, diff: .medium, q: "What programming language was developed by Sun Microsystems?", a: ["C++","Python","Ruby","Java"], c: 3),
        TriviaQ(id: 8016, cat: .technology, diff: .medium, q: "What is the name of the open-source Linux-based mobile OS?", a: ["Symbian","WebOS","Android","MeeGo"], c: 2),
        TriviaQ(id: 8017, cat: .technology, diff: .medium, q: "Who invented the telephone?", a: ["Thomas Edison","Nikola Tesla","Guglielmo Marconi","Alexander Graham Bell"], c: 3),
        TriviaQ(id: 8018, cat: .technology, diff: .medium, q: "What company introduced the first mass-market personal computer, the Apple II?", a: ["Commodore","IBM","Microsoft","Apple"], c: 3),
        TriviaQ(id: 8019, cat: .technology, diff: .medium, q: "What does 'GPU' stand for?", a: ["General Processing Unit","Graphical Performance Unit","Graphics Processing Unit","Grid Processing Unit"], c: 2),
        TriviaQ(id: 8020, cat: .technology, diff: .medium, q: "What was the original name of Google?", a: ["SearchBot","PageRank","BackRub","WebCrawler"], c: 2),
        TriviaQ(id: 8021, cat: .technology, diff: .hard, q: "What is the name of the encryption algorithm based on the difficulty of factoring large numbers?", a: ["AES","DES","RSA","SHA-256"], c: 2),
        TriviaQ(id: 8022, cat: .technology, diff: .hard, q: "What is Moore's Law?", a: ["Internet speed doubles every 18 months","The number of transistors on a chip doubles about every 2 years","Storage costs halve every 18 months","CPU clock speeds double every 3 years"], c: 1),
        TriviaQ(id: 8023, cat: .technology, diff: .hard, q: "What is the maximum number of bits in an IPv4 address?", a: ["16 bits","24 bits","32 bits","64 bits"], c: 2),
        TriviaQ(id: 8024, cat: .technology, diff: .medium, q: "What programming paradigm does Java primarily use?", a: ["Functional","Procedural","Object-Oriented","Declarative"], c: 2),
        TriviaQ(id: 8025, cat: .technology, diff: .easy, q: "What does 'PDF' stand for?", a: ["Portable Data Format","Print Document Format","Portable Document Format","Portable Data File"], c: 2),
        TriviaQ(id: 8026, cat: .technology, diff: .medium, q: "Who invented the World Wide Web?", a: ["Vint Cerf","Bob Kahn","Tim Berners-Lee","Marc Andreessen"], c: 2),
        TriviaQ(id: 8027, cat: .technology, diff: .hard, q: "What is the name of Linus Torvalds' famous open-source operating system kernel?", a: ["GNU","FreeBSD","Unix","Linux"], c: 3),
        TriviaQ(id: 8028, cat: .technology, diff: .medium, q: "What does the 'S' in HTTPS stand for?", a: ["Secure","Swift","Standard","Simple"], c: 0),
        TriviaQ(id: 8029, cat: .technology, diff: .easy, q: "What is the most popular search engine in the world?", a: ["Bing","Yahoo","DuckDuckGo","Google"], c: 3),
        TriviaQ(id: 8030, cat: .technology, diff: .hard, q: "What is the name of the theoretical computing device proposed by Alan Turing in 1936?", a: ["Universal Machine","Turing Machine","Analytical Engine","Digital Computer"], c: 1),
        TriviaQ(id: 8031, cat: .technology, diff: .medium, q: "What company invented the transistor in 1947?", a: ["IBM","GE","RCA","Bell Labs"], c: 3),
        TriviaQ(id: 8032, cat: .technology, diff: .easy, q: "What does 'Wi-Fi' stand for?", a: ["Wireless Fidelity","Wide Field","Wireless Field","Wire-Free Internet"], c: 0),
        TriviaQ(id: 8033, cat: .technology, diff: .medium, q: "What is the name of Apple's virtual assistant?", a: ["Alexa","Cortana","Google Assistant","Siri"], c: 3),
        TriviaQ(id: 8034, cat: .technology, diff: .hard, q: "In computing, what does 'BIOS' stand for?", a: ["Basic Integrated Operating System","Binary Input Output System","Basic Input Output System","Basic Internal Operating Software"], c: 2),
        TriviaQ(id: 8035, cat: .technology, diff: .medium, q: "What social network was founded by Mark Zuckerberg?", a: ["Twitter","LinkedIn","Myspace","Facebook"], c: 3),
        TriviaQ(id: 8036, cat: .technology, diff: .hard, q: "What is the hexadecimal representation of the decimal number 255?", a: ["FE","FD","FF","EF"], c: 2),
        TriviaQ(id: 8037, cat: .technology, diff: .easy, q: "What does 'VPN' stand for?", a: ["Virtual Private Network","Virtual Public Node","Verified Private Node","Virtual Protected Network"], c: 0),
        TriviaQ(id: 8038, cat: .technology, diff: .medium, q: "What is the name of Tesla's autopilot AI system?", a: ["Autopilot AI","Tesla Pilot","Full Self-Driving","Neural Driver"], c: 2),
        TriviaQ(id: 8039, cat: .technology, diff: .hard, q: "What programming language was created by Bjarne Stroustrup?", a: ["Java","Rust","C++","Go"], c: 2),
        TriviaQ(id: 8040, cat: .technology, diff: .medium, q: "What year was the first iPhone released?", a: ["2005","2006","2007","2008"], c: 2),
    ]}

    // MARK: — Food (9000–9059)
    private static var food: [TriviaQ] {[
        TriviaQ(id: 9001, cat: .food, diff: .easy, q: "What is the main ingredient in guacamole?", a: ["Tomato","Lime","Jalapeño","Avocado"], c: 3),
        TriviaQ(id: 9002, cat: .food, diff: .easy, q: "What country is sushi originally from?", a: ["China","Korea","Japan","Thailand"], c: 2),
        TriviaQ(id: 9003, cat: .food, diff: .easy, q: "What spice is used to make curry yellow?", a: ["Paprika","Saffron","Turmeric","Ginger"], c: 2),
        TriviaQ(id: 9004, cat: .food, diff: .easy, q: "What is the main ingredient in hummus?", a: ["Lentils","Chickpeas","White beans","Fava beans"], c: 1),
        TriviaQ(id: 9005, cat: .food, diff: .easy, q: "What fruit is used to make wine?", a: ["Apples","Pears","Grapes","Plums"], c: 2),
        TriviaQ(id: 9006, cat: .food, diff: .easy, q: "What is the Italian word for cheese used on pizza?", a: ["Parmesan","Ricotta","Gorgonzola","Mozzarella"], c: 3),
        TriviaQ(id: 9007, cat: .food, diff: .easy, q: "What type of nuts are used to make peanut butter?", a: ["Almonds","Cashews","Walnuts","Peanuts"], c: 3),
        TriviaQ(id: 9008, cat: .food, diff: .easy, q: "What is the most consumed meat in the world?", a: ["Beef","Chicken","Pork","Lamb"], c: 2),
        TriviaQ(id: 9009, cat: .food, diff: .easy, q: "What vegetable is used to make coleslaw?", a: ["Lettuce","Broccoli","Celery","Cabbage"], c: 3),
        TriviaQ(id: 9010, cat: .food, diff: .easy, q: "What is the main ingredient in French onion soup?", a: ["Leeks","Shallots","Onions","Garlic"], c: 2),
        TriviaQ(id: 9011, cat: .food, diff: .medium, q: "What dish is made from raw fish cured in citrus juices?", a: ["Sashimi","Tartare","Ceviche","Carpaccio"], c: 2),
        TriviaQ(id: 9012, cat: .food, diff: .medium, q: "What is the original country of origin for croissants?", a: ["France","Belgium","Austria","Switzerland"], c: 2),
        TriviaQ(id: 9013, cat: .food, diff: .medium, q: "What classic sauce is made from egg yolks, lemon juice, and butter?", a: ["Béarnaise","Hollandaise","Beurre blanc","Mousseline"], c: 1),
        TriviaQ(id: 9014, cat: .food, diff: .medium, q: "What gives Earl Grey tea its distinctive flavor?", a: ["Bergamot","Lavender","Jasmine","Rose"], c: 0),
        TriviaQ(id: 9015, cat: .food, diff: .medium, q: "What grain is used to make traditional Japanese sake?", a: ["Wheat","Barley","Millet","Rice"], c: 3),
        TriviaQ(id: 9016, cat: .food, diff: .medium, q: "What are the three primary ingredients in a traditional mirepoix?", a: ["Carrot, celery, leek","Onion, carrot, celery","Garlic, onion, bell pepper","Carrot, potato, parsnip"], c: 1),
        TriviaQ(id: 9017, cat: .food, diff: .medium, q: "What is the French culinary term for 'everything in its place' (prep work)?", a: ["Sous vide","Mise en place","Beurre noisette","Brunoise"], c: 1),
        TriviaQ(id: 9018, cat: .food, diff: .medium, q: "What country of origin does kimchi come from?", a: ["Japan","China","Vietnam","Korea"], c: 3),
        TriviaQ(id: 9019, cat: .food, diff: .medium, q: "What is the main protein in eggs?", a: ["Casein","Gluten","Albumin","Collagen"], c: 2),
        TriviaQ(id: 9020, cat: .food, diff: .medium, q: "What type of pasta is shaped like a small bow tie?", a: ["Rigatoni","Farfalle","Orecchiette","Fusilli"], c: 1),
        TriviaQ(id: 9021, cat: .food, diff: .hard, q: "What is the name of the traditional dish from Valencia, Spain that is considered the 'original' paella?", a: ["Paella Marinera","Paella Mixta","Paella Negra","Paella Valenciana"], c: 3),
        TriviaQ(id: 9022, cat: .food, diff: .hard, q: "What enzyme is responsible for making cheese from milk?", a: ["Protease","Amylase","Lactase","Rennet"], c: 3),
        TriviaQ(id: 9023, cat: .food, diff: .hard, q: "What is the Maillard reaction?", a: ["Caramelization of sugars","Browning reaction between amino acids and sugars","Oxidation of fats","Hydrolysis of starch"], c: 1),
        TriviaQ(id: 9024, cat: .food, diff: .medium, q: "What is the main ingredient in traditional miso soup?", a: ["Soy sauce","Dashi and miso paste","Fish sauce","Kombu seaweed"], c: 1),
        TriviaQ(id: 9025, cat: .food, diff: .easy, q: "What is the primary ingredient in traditional guacamole besides avocado?", a: ["Onion","Lime juice","Cilantro","Salt"], c: 1),
        TriviaQ(id: 9026, cat: .food, diff: .medium, q: "What cooking technique uses vacuum-sealed bags in temperature-controlled water?", a: ["Sous vide","Brine","Confit","Poach"], c: 0),
        TriviaQ(id: 9027, cat: .food, diff: .hard, q: "What is the name of the world's most expensive spice by weight?", a: ["Vanilla","Cardamom","Saffron","Truffle"], c: 2),
        TriviaQ(id: 9028, cat: .food, diff: .medium, q: "What country is the origin of baklava?", a: ["Greece","Turkey","Lebanon","Iran"], c: 1),
        TriviaQ(id: 9029, cat: .food, diff: .easy, q: "What nuts are used to make Nutella?", a: ["Almonds","Cashews","Hazelnuts","Walnuts"], c: 2),
        TriviaQ(id: 9030, cat: .food, diff: .hard, q: "What is the traditional Japanese cooking technique of grilling over charcoal?", a: ["Teriyaki","Hibachi","Teppanyaki","Yakitori"], c: 1),
        TriviaQ(id: 9031, cat: .food, diff: .medium, q: "What is the name of the deep-fried doughnut popular in New Orleans?", a: ["Churro","Fritter","Beignet","Zeppole"], c: 2),
        TriviaQ(id: 9032, cat: .food, diff: .easy, q: "What vegetable is used to make sauerkraut?", a: ["Pickles","Onions","Cabbage","Brussels sprouts"], c: 2),
        TriviaQ(id: 9033, cat: .food, diff: .medium, q: "What Italian dessert translates to 'pick me up' in English?", a: ["Panna cotta","Tiramisu","Cannoli","Zabaglione"], c: 1),
        TriviaQ(id: 9034, cat: .food, diff: .hard, q: "What is the chemical compound responsible for the heat in chili peppers?", a: ["Piperine","Allicin","Capsaicin","Gingerol"], c: 2),
        TriviaQ(id: 9035, cat: .food, diff: .medium, q: "What is the Indian flatbread cooked in a tandoor oven called?", a: ["Chapati","Paratha","Naan","Poori"], c: 2),
        TriviaQ(id: 9036, cat: .food, diff: .easy, q: "What fruit is the main ingredient in a Pina Colada?", a: ["Mango","Papaya","Coconut","Pineapple"], c: 3),
        TriviaQ(id: 9037, cat: .food, diff: .medium, q: "What cooking method involves submerging food in hot fat or oil?", a: ["Sauté","Broil","Deep fry","Braise"], c: 2),
        TriviaQ(id: 9038, cat: .food, diff: .hard, q: "What is the name of the Japanese dish made of thinly sliced raw beef?", a: ["Shabu-shabu","Sukiyaki","Yakitori","Gyukatsu (beef cutlet)"], c: 0),
        TriviaQ(id: 9039, cat: .food, diff: .easy, q: "What is the main ingredient in tzatziki sauce?", a: ["Sour cream","Crème fraîche","Greek yogurt","Ricotta"], c: 2),
        TriviaQ(id: 9040, cat: .food, diff: .medium, q: "What wine region in France is most famous for its Chardonnay and Pinot Noir?", a: ["Bordeaux","Champagne","Burgundy","Loire Valley"], c: 2),
    ]}

    // MARK: — Art (10000–10059)
    private static var art: [TriviaQ] {[
        TriviaQ(id: 10001, cat: .art, diff: .easy, q: "Who painted the Mona Lisa?", a: ["Raphael","Michelangelo","Leonardo da Vinci","Donatello"], c: 2),
        TriviaQ(id: 10002, cat: .art, diff: .easy, q: "What building in Paris is known for its glass pyramid entrance?", a: ["Centre Pompidou","Musée d'Orsay","Palais Royal","The Louvre"], c: 3),
        TriviaQ(id: 10003, cat: .art, diff: .easy, q: "Who painted 'The Starry Night'?", a: ["Paul Gauguin","Paul Cézanne","Claude Monet","Vincent van Gogh"], c: 3),
        TriviaQ(id: 10004, cat: .art, diff: .easy, q: "What Greek statue depicts the goddess of victory?", a: ["Venus de Milo","Laocoon","Winged Victory of Samothrace","Aphrodite of Knidos"], c: 2),
        TriviaQ(id: 10005, cat: .art, diff: .easy, q: "Who sculpted the statue of David?", a: ["Raphael","Donatello","Leonardo da Vinci","Michelangelo"], c: 3),
        TriviaQ(id: 10006, cat: .art, diff: .easy, q: "What art movement was Salvador Dali associated with?", a: ["Cubism","Impressionism","Surrealism","Expressionism"], c: 2),
        TriviaQ(id: 10007, cat: .art, diff: .easy, q: "What color is made by mixing blue and yellow?", a: ["Purple","Orange","Green","Brown"], c: 2),
        TriviaQ(id: 10008, cat: .art, diff: .easy, q: "What architectural wonder was built by the ancient Greeks in Athens?", a: ["Colosseum","Pantheon","Parthenon","Acropolis"], c: 2),
        TriviaQ(id: 10009, cat: .art, diff: .easy, q: "What artist is famous for painting water lilies?", a: ["Pierre-Auguste Renoir","Edgar Degas","Paul Cézanne","Claude Monet"], c: 3),
        TriviaQ(id: 10010, cat: .art, diff: .easy, q: "Who is known for painting the Sistine Chapel ceiling?", a: ["Raphael","Caravaggio","Leonardo da Vinci","Michelangelo"], c: 3),
        TriviaQ(id: 10011, cat: .art, diff: .medium, q: "What art movement was Pablo Picasso a co-founder of?", a: ["Fauvism","Futurism","Cubism","Expressionism"], c: 2),
        TriviaQ(id: 10012, cat: .art, diff: .medium, q: "What is the term for a building designed primarily for religious worship in Islam?", a: ["Synagogue","Temple","Cathedral","Mosque"], c: 3),
        TriviaQ(id: 10013, cat: .art, diff: .medium, q: "Who is the Spanish architect known for the Sagrada Família?", a: ["Rafael Moneo","Santiago Calatrava","Álvaro Siza","Antoni Gaudí"], c: 3),
        TriviaQ(id: 10014, cat: .art, diff: .medium, q: "What painting technique involves applying thick paint to the canvas?", a: ["Fresco","Watercolor","Impasto","Tempera"], c: 2),
        TriviaQ(id: 10015, cat: .art, diff: .medium, q: "What American artist is known for his giant Campbell's Soup Cans?", a: ["Roy Lichtenstein","Jasper Johns","Robert Rauschenberg","Andy Warhol"], c: 3),
        TriviaQ(id: 10016, cat: .art, diff: .medium, q: "What is the name of the art movement characterized by small, thin brushstrokes that captured light?", a: ["Post-Impressionism","Realism","Romanticism","Impressionism"], c: 3),
        TriviaQ(id: 10017, cat: .art, diff: .medium, q: "What artist cut off part of his ear?", a: ["Paul Gauguin","Paul Cézanne","Georges Seurat","Vincent van Gogh"], c: 3),
        TriviaQ(id: 10018, cat: .art, diff: .medium, q: "What is the name of Leonardo da Vinci's famous drawing showing human proportions?", a: ["The Last Supper","Madonna of the Rocks","Vitruvian Man","The Annunciation"], c: 2),
        TriviaQ(id: 10019, cat: .art, diff: .medium, q: "What architectural style is characterized by pointed arches, ribbed vaults, and flying buttresses?", a: ["Romanesque","Byzantine","Gothic","Baroque"], c: 2),
        TriviaQ(id: 10020, cat: .art, diff: .medium, q: "What is the name for the art of folding paper into shapes?", a: ["Kirigami","Quilling","Origami","Papier-mâché"], c: 2),
        TriviaQ(id: 10021, cat: .art, diff: .hard, q: "What is the name of the German art school founded by Walter Gropius in 1919?", a: ["De Stijl","Art Nouveau","Bauhaus","Vienna Secession"], c: 2),
        TriviaQ(id: 10022, cat: .art, diff: .hard, q: "What Mexican painter is famous for self-portraits and works depicting Mexican folk culture?", a: ["Diego Rivera","David Alfaro Siqueiros","Rufino Tamayo","Frida Kahlo"], c: 3),
        TriviaQ(id: 10023, cat: .art, diff: .hard, q: "What is the term for the vanishing point perspective technique developed in the Renaissance?", a: ["Chiaroscuro","Linear perspective","Foreshortening","Trompe l'oeil"], c: 1),
        TriviaQ(id: 10024, cat: .art, diff: .medium, q: "What is the name of the famous street artist known for politically charged works?", a: ["Shepard Fairey","JR","Invader","Banksy"], c: 3),
        TriviaQ(id: 10025, cat: .art, diff: .easy, q: "What is the primary medium used in watercolor painting?", a: ["Oil","Acrylic","Gouache","Water-soluble pigments"], c: 3),
        TriviaQ(id: 10026, cat: .art, diff: .medium, q: "What is the name of the art movement that emphasized dreams and unconscious imagery?", a: ["Dadaism","Surrealism","Abstract Expressionism","Futurism"], c: 1),
        TriviaQ(id: 10027, cat: .art, diff: .hard, q: "What famous architect designed the Guggenheim Museum in Bilbao, Spain?", a: ["I.M. Pei","Renzo Piano","Frank Lloyd Wright","Frank Gehry"], c: 3),
        TriviaQ(id: 10028, cat: .art, diff: .medium, q: "What painting does the acronym 'MONA LISA' stand for?", a: ["It means 'My Lady Lisa' in Italian","Madam Lisa, wife of Francesco del Giocondo","It's an abbreviation of Mona (Madonna) Lisa","Actually named La Gioconda"], c: 3),
        TriviaQ(id: 10029, cat: .art, diff: .easy, q: "What shape are the dots in pointillist paintings?", a: ["Squares","Small dots","Dashes","Circles"], c: 1),
        TriviaQ(id: 10030, cat: .art, diff: .hard, q: "Who painted 'The Birth of Venus'?", a: ["Leonardo da Vinci","Raphael","Titian","Sandro Botticelli"], c: 3),
        TriviaQ(id: 10031, cat: .art, diff: .medium, q: "What art period followed the Renaissance?", a: ["Neoclassicism","Romanticism","Mannerism","Baroque"], c: 3),
        TriviaQ(id: 10032, cat: .art, diff: .medium, q: "What ancient civilization built the Sphinx?", a: ["Mesopotamian","Roman","Greek","Egyptian"], c: 3),
        TriviaQ(id: 10033, cat: .art, diff: .hard, q: "Who painted 'Las Meninas', a famous Baroque painting?", a: ["El Greco","Francisco Goya","Francisco de Zurbarán","Diego Velázquez"], c: 3),
        TriviaQ(id: 10034, cat: .art, diff: .medium, q: "What is the name of the famous dome-capped mosque in Istanbul?", a: ["Süleymaniye Mosque","Selimiye Mosque","Blue Mosque","Hagia Sophia"], c: 3),
        TriviaQ(id: 10035, cat: .art, diff: .hard, q: "What art movement was characterized by geometric shapes and primary colors, developed by Piet Mondrian?", a: ["Constructivism","De Stijl","Suprematism","Abstract Expressionism"], c: 1),
        TriviaQ(id: 10036, cat: .art, diff: .easy, q: "What building is known as the 'Eighth Wonder of the World' in New York City?", a: ["Statue of Liberty","Brooklyn Bridge","Empire State Building","Chrysler Building"], c: 2),
        TriviaQ(id: 10037, cat: .art, diff: .medium, q: "What is the name of the technique of painting on wet plaster?", a: ["Encaustic","Tempera","Secco","Fresco"], c: 3),
        TriviaQ(id: 10038, cat: .art, diff: .hard, q: "Who designed St. Peter's Basilica in Rome?", a: ["Raphael","Leonardo da Vinci","Brunelleschi","Michelangelo"], c: 3),
        TriviaQ(id: 10039, cat: .art, diff: .medium, q: "What Norwegian artist painted 'The Scream'?", a: ["Edvard Grieg","Johan Christian Dahl","Theodor Kittelsen","Edvard Munch"], c: 3),
        TriviaQ(id: 10040, cat: .art, diff: .medium, q: "What is the largest art museum in the world?", a: ["Metropolitan Museum of Art","British Museum","Hermitage Museum","The Louvre"], c: 3),
    ]}
}
